apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nbb-docfx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nbb-docfx
  template:
    metadata:
      labels:
        app: nbb-docfx
    spec:
      containers:
      - name: nbb-docfx
        image: tsacr.azurecr.io/nbb_docfx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 512Mi
      imagePullSecrets:
      - name: registrykey
---